development: &default
  host: ec2-23-23-224-174.compute-1.amazonaws.com
  database: d1bbmche52b3gt
  username: rigltdulqeahjz
  port: 5432
  password: 8YftpbJJwVy50KDT6iSfTkifQ-

test:
  <<: *default
  host: ec2-23-23-224-174.compute-1.amazonaws.com
  database: d1bbmche52b3gt
  username: rigltdulqeahjz
  port: 5432
  password: 8YftpbJJwVy50KDT6iSfTkifQ-

production:
  <<: *default
  host: ec2-23-23-224-174.compute-1.amazonaws.com
  database: d1bbmche52b3gt
  username: rigltdulqeahjz
  port: 5432
  password: 8YftpbJJwVy50KDT6iSfTkifQ-
