development: &default
  adapter: postgresql
  encoding: utf8
  database: service_development
  username: postgres
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: service_test

production:
  host: ec2-23-23-224-174.compute-1.amazonaws.com
  database: d1bbmche52b3gt
  username: rigltdulqeahjz
  port: 5432
  password: 8YftpbJJwVy50KDT6iSfTkifQ-
